const languageTexts = {
  ko: {
    premierLeague: '프리미어리그',
    laLiga: '라리가',
    bundesliga: '분데스리가',
    serieA: '세리에 A',
    ligue1: '리그 1',
    season: '2023/24 시즌 팀 순위',
    rank: '순위',
    team: '팀',
    matches: '경기',
    wins: '승',
    draws: '무',
    losses: '패',
    goalsFor: '득점',
    goalsAgainst: '실점',
    goalDifference: '득실차',
    points: '승점',
    championsLeague: '챔피언스 리그',
    europaLeague: '유로파 리그',
    conferenceLeague: '컨퍼런스 리그',
    relegation: '강등 직행',
    month: '월',
    record: '기록',
    days: ['일', '월', '화', '수', '목', '금', '토'],
    status: { scheduled: '예정', ended: '종료' },
    home: '홈',
    firstHalf: '전반전',
    secondHalf: '후반전',
    power: '전력',
    lineup: '라인업',
    relay_broadcast: '중계',
    video: '영상',
    first_half: '전반전',
    second_half: '후반전',
  },
  ja: {
    premierLeague: 'プレミアリーグ',
    laLiga: 'ラ・リーガ',
    bundesliga: 'ブンデスリーガ',
    serieA: 'セリエ A',
    ligue1: 'リーグ 1',
    season: '2023/24 シーズン チーム順位',
    rank: '順位',
    team: 'チーム',
    matches: '試合',
    wins: '勝',
    draws: '引き分け',
    losses: '負け',
    goalsFor: '得点',
    goalsAgainst: '失点',
    goalDifference: '得失点差',
    points: 'ポイント',
    championsLeague: 'チャンピオンズリーグ',
    europaLeague: 'ヨーロッパリーグ',
    conferenceLeague: 'カンファレンスリーグ',
    relegation: '降格',
    month: '月',
    record: '記録',
    days: ['日', '月', '火', '水', '木', '金', '土'],
    status: { scheduled: '予定', ended: '終了' },
    home: 'ホーム',
    firstHalf: '前半',
    secondHalf: '後半',
    power: 'パワー',
    lineup: 'ラインナップ',
    relay_broadcast: '中継',
    video: '映像',
    first_half: '前半',
    second_half: '後半',
  },
  en: {
    premierLeague: 'Premier League',
    laLiga: 'La Liga',
    bundesliga: 'Bundesliga',
    serieA: 'Serie A',
    ligue1: 'Ligue 1',
    season: '2023/24 Season Team Standings',
    rank: 'Rank',
    team: 'Team',
    matches: 'Matches',
    wins: 'Wins',
    draws: 'Draws',
    losses: 'Losses',
    goalsFor: 'Goals For',
    goalsAgainst: 'Goals Against',
    goalDifference: 'Goal Difference',
    points: 'Points',
    championsLeague: 'Champions League',
    europaLeague: 'Europa League',
    conferenceLeague: 'Conference League',
    relegation: 'Relegation',
    month: 'Month',
    record: 'Record',
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    status: { scheduled: 'Scheduled', ended: 'Ended' },
    home: 'Home',
    firstHalf: 'First Half',
    secondHalf: 'Second Half',
    power: 'power',
    lineup: 'lineup',
    relay_broadcast: 'relay broadcast',
    video: 'video',
    first_half: 'First Half',
    second_half: 'Second Half',
  }
};

export default languageTexts;
